### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by danilolab** [Thalita-Carnicell/BASE#1]
Deixo como sugestão os seguintes tópicos:
- [ ] Continuar com a implementação do projeto
- [ ] Aprofundar os estudos no Angular, quanto à modularização e componentização
- [ ] Escrever os testes unitários
- [ ] Estudar um pouco mais das propriedades CSS
- [ ] Criar projetos pessoais, para crianças e/ou familiares e publicar no git para demonstrar seus conhecimentos
- [ ] Refazer alguns exercícios da GYM focados em design e backend
- [ ] Recomendação de sites: https://www.hackerrank.com/, https://leetcode.com/ e https://www.codewars.com/
